name: Spillhuset
main: com.spillhuset.oddjob.OddJob
version: 0.3
api-version: 1.18

commands:
  homes:
    description: Homes
  guilds:
    description: Guilds
  suicide:
    description: Suicide mother f***er!
  teleport:
    description: Teleporters
  locks:
    description: Locking
  enderchest:
    description: Looting
  invsee:
    description: Looting
  auctions:
    description: Auctions
  shops:
    description: Shops
  load:
    description: Loading
  warps:
    description: Warps
  currency:
    description: Currency