name: Spillhuset
main: com.spillhuset.oddjob.OddJob
version: 0.6
api-version: 1.19
softdepend:
  - dynmap
  - WorldEdit

commands:
  arena:
    description: Arena
  homes:
    description: Homes
  guilds:
    description: Guilds
  suicide:
    description: Suicide mother f***er!
  teleport:
    description: Teleport
  locks:
    description: Locking
  enderchest:
    description: Looting
  invsee:
    description: Looting
  auctions:
    description: Auctions
  shops:
    description: Shops
  load:
    description: Loading
  warps:
    description: Warps
  currency:
    description: Currency
  players:
    description: Players
  heal:
    description: Heals a player
  feed:
    description: Feeds a player
  sudo:
    description: Sudo
  world:
    description: World

permissions:
  homes:
    default: true
  homes.add:
    default: true
  homes.add.others:
    default: op
  homes.rename:
    default: true
  homes.rename.others:
    default: op
  homes.list:
    default: true
  homes.list.others:
    default: op
  homes.change:
    default: true
  homes.change.others:
    default: op
  homes.del:
    default: true
  homes.del.others:
    default: op
  homes.teleport:
    default: true
  homes.teleport.others:
    default: op