name: Spillhuset
main: com.spillhuset.oddjob.OddJob
version: 0.2
api-version: 1.18

commands:
  homes:
    description: Homes
  guilds:
    description: Guilds
  suicide:
    description: Suicide mother f***er!