name: Spillhuset
main: com.spillhuset.oddjob.OddJob
version: 0.5
api-version: 1.18
depend:
  - dynmap
  - WorldEdit

commands:
  arena:
    description: Arena
  homes:
    description: Homes
  guilds:
    description: Guilds
  suicide:
    description: Suicide mother f***er!
  teleport:
    description: Teleport
  locks:
    description: Locking
  enderchest:
    description: Looting
  invsee:
    description: Looting
  auctions:
    description: Auctions
  shops:
    description: Shops
  load:
    description: Loading
  warps:
    description: Warps
  currency:
    description: Currency
  players:
    description: Players
  heal:
    description: Heals a player
  feed:
    description: Feeds a player
  sudo:
    description: Sudo
  world:
    description: World