package com.spillhuset.oddjob.Enums;

public enum Containers {
    ANVIL, BARREL, BEACON, BEE_NEST, BEEHIVE, BLACK_SHULKER_BOX, BLAST_FURNACE, BLUE_SHULKER_BOX, BREWING_STAND, BROWN_SHULKER_BOX, CAMPFIRE, CARTOGRAPHY_TABLE, CHEST, CHIPPED_ANVIL, COMPOSTER, CYAN_SHULKER_BOX, DAMAGED_ANVIL, DISPENSER, DROPPER, ENCHANTING_TABLE, ENDER_CHEST, FLETCHING_TABLE, FURNACE, GRAY_SHULKER_BOX, GREEN_SHULKER_BOX, GRINDSTONE, HOPPER, JUKEBOX, LECTERN, LIGHT_BLUE_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, LIME_SHULKER_BOX, LOOM, MAGENTA_SHULKER_BOX, ORANGE_SHULKER_BOX, PINK_SHULKER_BOX, PURPLE_SHULKER_BOX, RED_SHULKER_BOX, SHULKER_BOX, SMITHING_TABLE, SMOKER, SOUL_CAMPFIRE, STONECUTTER, TRAPPED_CHEST, WHITE_SHULKER_BOX, YELLOW_SHULKER_BOX
}
